name: Snake
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
     build:
      name: Jobs to Init Snake
      runs-on: ubuntu-latest
      steps:
        - uses: Platane/snk@v3
          with: 
           github_user_name: matheus-brasil11
           outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

          env: 
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
